const icons = {
  space: String.fromCodePoint(0x00a0), // &nbsp;
  copyright: String.fromCodePoint(0x00a9), // ©
  keyboard: String.fromCodePoint(0x2328), // ⌨
  copy: String.fromCodePoint(0x2398), // ⎘
  paste: String.fromCodePoint(0x2399), // ⎙
  cut: String.fromCodePoint(0x2702), // ✂
  save: String.fromCodePoint(0x1f4be), // 💾
  delete: String.fromCodePoint(0x1f5d1), // 🗑
  undo: String.fromCodePoint(0x21b6), // ↶
  redo: String.fromCodePoint(0x21b7), // ↷
  search: String.fromCodePoint(0x1f50d), // 🔍
  settings: String.fromCodePoint(0x2699), // ⚙
  home: String.fromCodePoint(0x1f3e0), // 🏠
  user: String.fromCodePoint(0x1f464), // 👤
  info: String.fromCodePoint(0x2139), // ℹ
  warning: String.fromCodePoint(0x26a0), // ⚠
  error: String.fromCodePoint(0x1f6ab), // 🚫
  success: String.fromCodePoint(0x2705), // ✅
  upload: String.fromCodePoint(0x1f4e4), // 📤
  download: String.fromCodePoint(0x1f4e5), // 📥
  print: String.fromCodePoint(0x2399), // ⎙
  power: String.fromCodePoint(0x23fb), // ⏻
  wifi: String.fromCodePoint(0x1f4f6), // 📶
  battery: String.fromCodePoint(0x1f50b), // 🔋
  volumeUp: String.fromCodePoint(0x1f50a), // 🔊
  volumeDown: String.fromCodePoint(0x1f509), // 🔉
  mute: String.fromCodePoint(0x1f507), // 🔇
  lock: String.fromCodePoint(0x1f512), // 🔒
  unlock: String.fromCodePoint(0x1f513), // 🔓
  play: String.fromCodePoint(0x25b6), // ▶
  pause: String.fromCodePoint(0x23f8), // ⏸
  stop: String.fromCodePoint(0x23f9), // ⏹
  record: String.fromCodePoint(0x23fa), // ⏺
  forward: String.fromCodePoint(0x23e9), // ⏩
  rewind: String.fromCodePoint(0x23ea), // ⏪
  calendar: String.fromCodePoint(0x1f4c5), // 📅
  clock: String.fromCodePoint(0x1f552), // 🕒
  edit: String.fromCodePoint(0x270d), // ✍
  camera: String.fromCodePoint(0x1f4f7), // 📷
  heart: String.fromCodePoint(0x2764), // ❤
  star: String.fromCodePoint(0x2b50), // ⭐
  bookmark: String.fromCodePoint(0x1f516), // 🔖
  trash: String.fromCodePoint(0x1f5d1), // 🗑
  mail: String.fromCodePoint(0x1f4e7), // 📧
  phone: String.fromCodePoint(0x1f4de), // 📞
  map: String.fromCodePoint(0x1f5fa), // 🗺
  location: String.fromCodePoint(0x1f4cd), // 📍
  globe: String.fromCodePoint(0x1f310), // 🌐
  sun: String.fromCodePoint(0x2600), // ☀
  moon: String.fromCodePoint(0x1f319), // 🌙
  cloud: String.fromCodePoint(0x2601), // ☁
  rain: String.fromCodePoint(0x1f327), // 🌧
  snow: String.fromCodePoint(0x1f328), // 🌨
  fire: String.fromCodePoint(0x1f525), // 🔥
  rocket: String.fromCodePoint(0x1f680), // 🚀
  check: String.fromCodePoint(0x2714), // ✔
  cross: String.fromCodePoint(0x274c), // ❌
  question: String.fromCodePoint(0x2753), // ❓
  exclamation: String.fromCodePoint(0x2757), // ❗
  smile: String.fromCodePoint(0x1f600), // 😀
  sad: String.fromCodePoint(0x1f641), // 🙁
  thumbsUp: String.fromCodePoint(0x1f44d), // 👍
  thumbsDown: String.fromCodePoint(0x1f44e), // 👎
  money: String.fromCodePoint(0x1f4b0), // 💰
  gift: String.fromCodePoint(0x1f381), // 🎁
  music: String.fromCodePoint(0x1f3b5), // 🎵
  video: String.fromCodePoint(0x1f4f9), // 📹
};
export default icons;
